FROM debian:bullseye

RUN apt update && apt install -y \
    python3 \
    python3-pip \
    python3-numpy \
    python3-pandas \
    python3-sklearn \
    python3-joblib \
    python3-scipy \
    nano \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace